package laits.gui.dialog;

import laits.Main;
import laits.model.GraphCanvas;

import java.awt.Frame;
import java.io.File;
import java.util.LinkedList;
import java.util.logging.Level;
import javax.swing.JDialog;
import metatutor.Query;
import org.apache.log4j.Logger;

/**
 * Verifies whether the user wants to exit the program
 *
 * @author Megan Kearl
 * @version 20100331
 *
 */
public class ExitDialog extends JDialog {

  private Frame p;
//  private GraphCanvas gc;
  boolean closingSet = false;
//  boolean closing = false;
  private int Points;
  private static Logger logs = Logger.getLogger(ExitDialog.class);

  /**
   * Creates new form ExitDialog Form
   */
  public ExitDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    p = parent;
    this.setTitle("");
    initComponents();
    this.setLocationRelativeTo(parent);
    LinkedList<laits.gui.NodeEditor> openTabs = GraphCanvas.getOpenTabs();
    for (int i = 0; i < openTabs.size(); i++) {
      openTabs.get(i).setAlwaysOnTop(false);
    }
    openTabs.clear();
    this.pack();
  }

  public boolean closingSet() {
    return closingSet();
  }

  public void closing() {
     p.dispose();
     this.dispose();
     System.exit(0);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Are you sure you would like to exit?");

        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(yesButton)
                .addGap(18, 18, 18)
                .addComponent(noButton)
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed

    closing();

   }//GEN-LAST:event_yesButtonActionPerformed

   private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
     LinkedList<laits.gui.NodeEditor> openTabs = GraphCanvas.getOpenTabs();
     for (int i = 0; i < openTabs.size(); i++) {
       openTabs.get(i).setAlwaysOnTop(true);
     }
     openTabs.clear();
     this.dispose();
   }//GEN-LAST:event_noButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
