/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amt.gui.dialog;

import amt.ApplicationUser;
import laits.graph.Graph;
import org.apache.log4j.Logger;

/**
 *
 * @author ramayantiwari
 */
public class UserRegistration extends javax.swing.JDialog {

  /**
   * Creates new form UserRegistration2
   */
  public UserRegistration(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    
    setLocationRelativeTo(null);
    hideErrorMessages();
    setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    firstnameInputBox = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    firstnameErrMsg = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    asuidInputBox = new javax.swing.JTextField();
    lastnameInputBox = new javax.swing.JTextField();
    lastnameErrMsg = new javax.swing.JLabel();
    spacer = new javax.swing.JLabel();
    buttonSubmit = new javax.swing.JButton();
    buttonCancel = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    asuidErrMsg = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("AMT User Registration");
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    getContentPane().add(firstnameInputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 61, 158, -1));

    jLabel1.setText("First Name*: ");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 67, 90, -1));

    firstnameErrMsg.setForeground(new java.awt.Color(250, 0, 0));
    firstnameErrMsg.setText("jLabel5");
    getContentPane().add(firstnameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 89, -1));

    jLabel2.setText("Last Name*: ");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 113, -1, -1));

    jLabel3.setText("ASU ID*: ");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 159, 80, -1));
    getContentPane().add(asuidInputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 153, 158, -1));
    getContentPane().add(lastnameInputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 107, 158, -1));

    lastnameErrMsg.setForeground(new java.awt.Color(255, 0, 0));
    lastnameErrMsg.setText("jLabel5");
    getContentPane().add(lastnameErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 89, -1));

    spacer.setForeground(new java.awt.Color(252, 0, 0));
    spacer.setText("      ");
    getContentPane().add(spacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 256, 89, 20));

    buttonSubmit.setText("Submit");
    buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonSubmitActionPerformed(evt);
      }
    });
    getContentPane().add(buttonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 212, -1, -1));

    buttonCancel.setText("Cancel");
    buttonCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonCancelActionPerformed(evt);
      }
    });
    getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 212, -1, -1));

    jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel4.setText("User Registration");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 0, 169, 37));

    asuidErrMsg.setForeground(new java.awt.Color(252, 0, 0));
    asuidErrMsg.setText("jLabel5");
    getContentPane().add(asuidErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 89, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
    // TODO add your handling code here:
    hideErrorMessages();
    
    String firstName = firstnameInputBox.getText();
    String lastName = lastnameInputBox.getText();
    String asuId = asuidInputBox.getText();
    
    if(validateInputFields(firstName,lastName,asuId)){
      logs.trace("User Registration Successful");
      ApplicationUser.setUserFirstName(firstName);
      ApplicationUser.setUserLastName(lastName);
      ApplicationUser.setUserASUID(asuId);
      
      ApplicationUser.setUserValid(true);
      
      this.dispose();
    }
  }//GEN-LAST:event_buttonSubmitActionPerformed

  private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
    // TODO add your handling code here:
    this.dispose();
  }//GEN-LAST:event_buttonCancelActionPerformed

  
  private boolean validateInputFields(String fName, String lName, String id){
    boolean formHasErr = false;
    
    if(fName == null || fName.isEmpty()){
      firstnameErrMsg.setText(" Required ");
      firstnameErrMsg.setVisible(true);
      formHasErr = true;
    }
    
    if(lName == null || lName.isEmpty()){
      lastnameErrMsg.setText(" Required ");
      lastnameErrMsg.setVisible(true);
      formHasErr = true;
    }
    
    if(id == null || id.isEmpty()){
      asuidErrMsg.setText(" Required ");
      asuidErrMsg.setVisible(true);
      formHasErr = true;
    }else{
      if(id.length() != 10 || !isInteger(id)){
        asuidErrMsg.setText(" Invalid ");
        asuidErrMsg.setVisible(true);
        formHasErr = true;
      }
    }
    
    return !formHasErr;
  }
  
  private void hideErrorMessages(){
    firstnameErrMsg.setVisible(false);
    lastnameErrMsg.setVisible(false);
    asuidErrMsg.setVisible(false);
  }  
  
  
  /**
   * Method to test if String contains only Integers
   * @param input: String to test
   * @return 
   */
  private boolean isInteger(String input){
    try{
      Integer.parseInt(input);
      return true;
    }catch(Exception e){
      return false;
    }
  } 
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel asuidErrMsg;
  private javax.swing.JTextField asuidInputBox;
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonSubmit;
  private javax.swing.JLabel firstnameErrMsg;
  private javax.swing.JTextField firstnameInputBox;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel lastnameErrMsg;
  private javax.swing.JTextField lastnameInputBox;
  private javax.swing.JLabel spacer;
  // End of variables declaration//GEN-END:variables

  /** Logger **/
  private static Logger logs = Logger.getLogger(UserRegistration.class);
}
