package metatutor;

import amt.Main;
import amt.Main;
import amt.graph.GraphCanvas;
import amt.log.Logger;
import java.util.LinkedList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JRootPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MetaTutorMsg.java
 *
 * Created on May 18, 2011, 11:31:01 AM
 */

/**
 *
 * @author Lishan
 */
public class MetaTutorMsg extends javax.swing.JDialog {

  private boolean addToMemo=true;
  private Logger logger=Logger.getLogger();
  private String content="";

  /** Creates new form MetaTutorMsg */
  public MetaTutorMsg(String content) //used by metatutorprinciple
  {
    initComponents();
    this.setModal(true);
    this.content=content;
  }

  public void display(){
    if(content.equals(""))
      return;
    
      this.setLocationByPlatform(true);
        this.quesTxt.setText("<html>"+content+"</html>");
        this.quesTxt.setFocusable(false);
        //this.setSize(300, (content.length()/50+1)*20+120);
        this.setLocationRelativeTo(null);
        this.update(this.getGraphics());
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);

          this.setName("tutorMsg");
        Main.dialogIsShowing=true;
        for(int i=0;i<GraphCanvas.getOpenTabs().size();i++)
          GraphCanvas.getOpenTabs().get(i).setEnabled(false);

        
         this.setAlwaysOnTop(true);
         this.setVisible(true);
  }

    public MetaTutorMsg(String content, boolean addToMemo) {
      this.addToMemo=addToMemo;
      if(addToMemo)
        Main.getMemo().append("\nTutor said: "+content+"\n");
      else
       logger.concatOut(Logger.ACTIVITY, "No message", "Meta tutor denies the action.");

      initComponents();

        this.setLocationByPlatform(true);
        this.quesTxt.setText("<html>"+content+"</html>");
        this.quesTxt.setFocusable(false);
        //this.setSize(300, (content.length()/50+1)*20+120);
        this.setLocationRelativeTo(null);
        this.update(this.getGraphics());
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);

   //     if(this.addToMemo){
          this.setName("tutorMsg");
        Main.dialogIsShowing=true;
        LinkedList<amt.gui.NodeEditor> openTabs = GraphCanvas.getOpenTabs();
        for(int i=0;i<openTabs.size();i++)
          openTabs.get(i).setEnabled(false);
 //       }
         this.setAlwaysOnTop(true);
         
         this.setModal(true);
         this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        quesTxt = new javax.swing.JLabel();

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        quesTxt.setToolTipText("");
        quesTxt.setAutoscrolls(true);
        quesTxt.setMinimumSize(new java.awt.Dimension(100, 18));
        quesTxt.setPreferredSize(new java.awt.Dimension(100, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1)
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(quesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // if(this.addToMemo){
      Main.dialogIsShowing=false;
      LinkedList<amt.gui.NodeEditor> openTabs = GraphCanvas.getOpenTabs();
      for(int i=0;i<openTabs.size();i++)
        openTabs.get(i).setEnabled(true);
   //   }
      
      this.setVisible(false);
      this.setName("closed");
      if(openTabs.size()>0)
        openTabs.get(0).setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetaTutorMsg("\n     t test test test", false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel quesTxt;
    // End of variables declaration//GEN-END:variables

}
