/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MetaTutorQues.java
 *
 * Created on May 11, 2011, 2:27:21 PM
 */

package metatutor;

import amt.Main;
import amt.gui.PlanPanel;
import amt.graph.GraphCanvas;
import amt.log.Logger;
import java.util.LinkedList;
import java.util.logging.Level;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextArea;
import metatutor.Query;
import metatutor.MetaTutorMsg;

/**
 *
 * @author Lishan
 */
public class MetaTutorQues extends javax.swing.JDialog {

    /** Creates new form MetaTutorQues */
  private Logger logger=Logger.getLogger();
  private Query blockQuery=Query.getBlockQuery();

    public MetaTutorQues(String quesStr, String []option) {
      if(quesStr.contains("@@")){
        logger.concatOut(Logger.ACTIVITY,"No message","Dialog from Meta Tutor: "+quesStr.split("@@")[1]);
        quesStr=quesStr.split("@@")[0];
        
      }

      Main.getMemo().append("\nTutor said: "+quesStr+"\n");

      initComponents();
      
        this.setLocationRelativeTo(null);
        this.quesTxt.setText("\n"+quesStr);
        this.optionComb.removeAllItems();
        for(int i=0;i<option.length;i++)
          this.optionComb.addItem(option[i]);
        this.quesTxt.setFocusable(false);
        this.setSize(400,(1+quesStr.length()/50)*15+170);
        this.update(this.getGraphics());

        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);

        this.setName("tutorQues");
        Main.dialogIsShowing=true;
        LinkedList<amt.gui.NodeEditor> openTabs = GraphCanvas.getOpenTabs();
        for(int i=0;i<openTabs.size();i++)
          openTabs.get(i).setEnabled(false);
        this.setVisible(true);
        this.setAlwaysOnTop(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        optionComb = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        quesTxt = new javax.swing.JTextArea();

        jLabel1.setText("Please select your answer: ");

        optionComb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        quesTxt.setBackground(new java.awt.Color(240, 240, 240));
        quesTxt.setColumns(10);
        quesTxt.setEditable(false);
        quesTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quesTxt.setLineWrap(true);
        quesTxt.setRows(5);
        quesTxt.setWrapStyleWord(true);
        quesTxt.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quesTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionComb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(optionComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        quesTxt.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(this.optionComb.getSelectedIndex()==0)
      {
        JOptionPane.showMessageDialog(this, "Please select your answer.");
        return;
      }

      boolean newDia=false;
      try {
      LinkedList<amt.gui.NodeEditor> openTabs = GraphCanvas.getOpenTabs();
      for(int i=0;i<openTabs.size();i++)
        openTabs.get(i).setEnabled(true);
      
      // submit action:
      
      logger.concatOut(Logger.ACTIVITY, "No message", "Submit answer try--" + this.optionComb.getSelectedIndex());
      Thread.sleep(50);
      String returnMsg = blockQuery.listen("Submit answer");
      Main.getMemo().append("\nYou answered: "+this.optionComb.getSelectedItem()+".\n");
      if (returnMsg.startsWith("deny:")) {
        new MetaTutorMsg(returnMsg.split(":")[1],true).setVisible(true);
        logger.concatOut(Logger.ACTIVITY, "No message", "Student answered meta tutor's question wrongly.");
        newDia=true;
      }
      else if (returnMsg.startsWith("allow:")){
        new MetaTutorMsg(returnMsg.split(":")[1],true).setVisible(true);
        logger.concatOut(Logger.ACTIVITY, "No message", "Student answered meta tutor's question correctly.");
        newDia=true;
      }
      else if (returnMsg.startsWith("newdialog::")){
        String ques=returnMsg.split("::")[1];
        String []options=returnMsg.split("::")[2].split(",");
        if(ques.trim().toLowerCase().startsWith("the selection you just made is incorrect"))
          logger.concatOut(Logger.ACTIVITY, "No message", "Student answered meta tutor's question wrongly.");
        else
          logger.concatOut(Logger.ACTIVITY, "No message", "Student answered meta tutor's question correctly.");
        
        new MetaTutorQues(ques,options).setVisible(true);
        newDia=true;
      }
      else if (returnMsg.startsWith("principleSel::")){
        String message=returnMsg.split("::")[1];

       //new Plan(message).display();
       // newDia=true;
      }
    } catch (InterruptedException ex) {
      java.util.logging.Logger.getLogger(MetaTutorQues.class.getName()).log(Level.SEVERE, null, ex);
    }

    
    this.setVisible(false);
    this.setName("closed");
    if(!newDia){
      Main.dialogIsShowing=false;
      LinkedList<amt.gui.NodeEditor> openTabs = GraphCanvas.getOpenTabs();
      if(openTabs.size()>0)
        openTabs.get(0).setVisible(true);
      }
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
              String []ops={"a","b"};
              new MetaTutorQues("test question.", ops).setVisible(true);
              System.out.println("run");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox optionComb;
    private javax.swing.JTextArea quesTxt;
    // End of variables declaration//GEN-END:variables

}
