/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CorrectAnswerPanel.java
 *
 * Created on Dec 5, 2010, 5:13:46 PM
 */

package laits.gui;

import laits.Main;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author Megana
 */
public class CorrectAnswerPanel extends javax.swing.JPanel {

    Image correctAnswer = null;
    GraphsPanel parent = null;
    boolean resized = false;
    /** Creates new form CorrectAnswerPanel */
    public CorrectAnswerPanel(GraphsPanel parent) 
    {
        initComponents();
        this.parent = parent;
        String temp = "images/sampleCorrectGraph.png";
        URL imageURL = Main.class.getResource(temp);
        correctAnswer = Toolkit.getDefaultToolkit().createImage(imageURL);
    }

  @Override
    public int getWidth()
    {
      return correctAnswer.getWidth(this);
    }

  @Override
    public int getHeight()
    {
      return correctAnswer.getHeight(this);
    }

    @Override
    public void paint(Graphics g)
    {
      g.drawImage(correctAnswer, 0, 0, 300, 200, this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
