/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MetaTutorPrinciples.java
 *
 * Created on Oct 5, 2011, 11:40:19 PM
 */
package laits.gui;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JRadioButton;
import laits.graph.Graph;
import laits.graph.GraphCanvas;
import laits.graph.Vertex;
import laits.log.Logger;

import laits.parser.Branch;
import laits.parser.PlanTree;

/**
 *
 * @author Lishan
 */
public class Plan extends javax.swing.JPanel {

    private Logger logger = Logger.getLogger();
    private String message = "";
    private NodeEditor parent;
    private Vertex currentVertex;
    private Graph g;
    private GraphCanvas gc;
    PlanTree pt;
    JRadioButton optRadio[];
    Branch branch;
    int currentLevel = 0;
    private ArrayList<String> traversedList;

    public Plan(NodeEditor parent, Vertex v, Graph g, GraphCanvas gc) {
        this.parent = parent;
        this.g = g;
        this.gc = gc;
        this.currentVertex = v;
        initComponents();
        this.setVisible(true);

        pt = PlanTree.getPlanTree(currentVertex.getNodeName());
        optRadio = new JRadioButton[5];

        branch = pt.branches.get(0);
        traversedList = new ArrayList<String>();
    }

    public void initializePlan() {

        // Setting the text of Title
        String title = "Is \"" + currentVertex.getNodeName() + "\" a : ";
        titleLabel.setText(title);

        Set set = branch.forks.entrySet();

        Iterator it = set.iterator();

        optRadio[0] = optButton1;
        optRadio[1] = optButton2;
        optRadio[2] = optButton3;
        optRadio[3] = optButton4;
        optRadio[4] = optButton5;


        for (int i = 0; i < optRadio.length; i++) {
            optRadio[i].setVisible(false);
        }
        // Initiating count backword as branches are coming from end to start
        int count = set.size() - 1;

        while (it.hasNext()) {
            Map.Entry me = (Map.Entry) it.next();
            optRadio[count].setText(String.valueOf(me.getKey()));
            optRadio[count].setVisible(true);

            if (branch.selectedFork == count) {
                optRadio[count].setSelected(true);
            } else {
                optRadio[count].setSelected(false);
            }
            count--;
        }


    }

    public void display() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        optionPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        optButton1 = new javax.swing.JRadioButton();
        optButton2 = new javax.swing.JRadioButton();
        optButton3 = new javax.swing.JRadioButton();
        optButton4 = new javax.swing.JRadioButton();
        optButton5 = new javax.swing.JRadioButton();
        cancelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("Title Text");
        titleLabel.setFocusable(false);

        buttonGroup1.add(optButton1);
        optButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(optButton2);
        optButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(optButton3);
        optButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(optButton4);
        optButton4.setText("    ");
        optButton4.setMaximumSize(new java.awt.Dimension(20, 22));
        optButton4.setMinimumSize(new java.awt.Dimension(20, 22));
        optButton4.setPreferredSize(new java.awt.Dimension(20, 22));
        optButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(optButton5);
        optButton5.setText("     ");
        optButton5.setMaximumSize(new java.awt.Dimension(20, 22));
        optButton5.setMinimumSize(new java.awt.Dimension(20, 22));
        optButton5.setPreferredSize(new java.awt.Dimension(20, 22));
        optButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(optButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)))
                .addGap(140, 140, 140))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titleLabel)
                .addGap(29, 29, 29)
                .addComponent(optButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84))
        );

        cancelButton.setText("Ok");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        prevButton.setText("Prev");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevButton)
                    .addComponent(cancelButton)
                    .addComponent(nextButton))
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // Next button action
        String selectedTarget = branch.forks.get(optRadio[branch.selectedFork].getText());
        if (traversedList.isEmpty()) {
            traversedList.add(branch.getId());
        } else {
            if (traversedList.get(traversedList.size() - 1).compareTo(branch.getId()) != 0) {
                traversedList.add(branch.getId());
            }
        }

        branch = null;
        for (int i = 1; i < pt.branches.size(); i++) {
            if (pt.branches.get(i).getId().compareTo(selectedTarget) == 0) {
                branch = pt.branches.get(i);
                break;
            }
        }
        if (branch == null) {
            nextButton.setEnabled(false);
            return;
        }
        // Setting the text of Title
        String title = branch.getContent();
        titleLabel.setText(title);

        Set set = branch.forks.entrySet();

        Iterator it = set.iterator();
        buttonGroup1.clearSelection();
        for (int i = 0; i < optRadio.length; i++) {
            optRadio[i].setVisible(false);
        }

        // Initiating count backword as branches are coming from end to start
        int count = set.size() - 1;

        while (it.hasNext()) {
            Map.Entry me = (Map.Entry) it.next();
            optRadio[count].setText(String.valueOf(me.getKey()));
            optRadio[count].setVisible(true);
            optRadio[count].setSelected(false);

            if (branch.selectedFork == count) {
                optRadio[count].setSelected(true);
            }
            count--;
        }
        prevButton.setEnabled(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // Prev button action
        String id = traversedList.get(traversedList.size() - 1);
        for (int i = 0; i < pt.branches.size(); i++) {
            if (pt.branches.get(i).getId().compareTo(id) == 0) {
                branch = pt.branches.get(i);
                break;
            }
        }

        // Setting the text of Title
        String title = branch.getContent();
        titleLabel.setText(title);

        Set set = branch.forks.entrySet();

        Iterator it = set.iterator();

        for (int i = 0; i < optRadio.length; i++) {
            optRadio[i].setVisible(false);
            optRadio[i].setSelected(false);
        }
        // Initiating count backword as branches are coming from end to start
        int count = set.size() - 1;

        while (it.hasNext()) {
            Map.Entry me = (Map.Entry) it.next();
            optRadio[count].setText(String.valueOf(me.getKey()));
            optRadio[count].setVisible(true);
            count--;
        }

        // Removing the traversed element from TravesedList
        traversedList.remove(traversedList.size() - 1);
        if (traversedList.isEmpty()) {
            prevButton.setEnabled(false);
            nextButton.setEnabled(true);
            String t = "Is \"" + currentVertex.getNodeName() + "\" a : ";
            titleLabel.setText(t);
        }
    }//GEN-LAST:event_prevButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        //Cancel button action
        parent.windowClosing(null);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void optButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optButton2ActionPerformed
        // TODO add your handling code here:
        branch.selectedFork = 1;
    }//GEN-LAST:event_optButton2ActionPerformed

    private void optButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optButton1ActionPerformed
        // TODO add your handling code here:
        branch.selectedFork = 0;
    }//GEN-LAST:event_optButton1ActionPerformed

    private void optButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optButton3ActionPerformed
        // TODO add your handling code here:
        branch.selectedFork = 2;
    }//GEN-LAST:event_optButton3ActionPerformed

    private void optButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optButton4ActionPerformed
        // TODO add your handling code here:
        branch.selectedFork = 3;
    }//GEN-LAST:event_optButton4ActionPerformed

    private void optButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optButton5ActionPerformed
        // TODO add your handling code here:
        branch.selectedFork = 4;
    }//GEN-LAST:event_optButton5ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton optButton1;
    private javax.swing.JRadioButton optButton2;
    private javax.swing.JRadioButton optButton3;
    private javax.swing.JRadioButton optButton4;
    private javax.swing.JRadioButton optButton5;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JButton prevButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
