/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TaskCreator.java
 *
 * Created on Oct 11, 2011, 4:10:33 PM
 */
package laits.gui;
import laits.comm.ImageFilter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URL;
import javax.swing.*;

/**
 *
 * @author Ram
 */
public class TaskCreator extends javax.swing.JPanel 
                                implements ActionListener {

    JFileChooser fc;
            
    /** Creates new form TaskCreator */
    public TaskCreator() {
        fc = new JFileChooser();
        
        initComponents();
        buttonFileOpen.addActionListener(this);
        buttonEditMode.addActionListener(this);
        buttonPreviewMode.addActionListener(this);
        
        
        // Disabling Edit button in the start
        buttonEditMode.setEnabled(false);
        labelPreview.setVisible(false);
    }

    public void actionPerformed(ActionEvent e) {

         if (e.getSource() == buttonFileOpen) {
                fc.addChoosableFileFilter(new ImageFilter());
                fc.setAcceptAllFileFilterUsed(false);
              int returnVal = fc.showOpenDialog(TaskCreator.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                
                File file = fc.getSelectedFile();
                labelFileUrl.setText(file.getPath());                
            }else{
                labelFileUrl.setText("No File Selected.");
            }
         }else if(e.getSource() == buttonEditMode){
             
         }else if(e.getSource() == buttonPreviewMode){
             
         }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPreview = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonFileOpen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelFileUrl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonEditMode = new javax.swing.JButton();
        buttonPreviewMode = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(936, 700));

        labelPreview.setText("Preview");

        jLabel1.setText("Problem Description");

        buttonFileOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amt/images/Open16.gif"))); // NOI18N
        buttonFileOpen.setText("Open a File");

        jLabel2.setText("Problem Image");

        labelFileUrl.setText("No File Selected.");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonFileOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFileUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addGap(114, 114, 114))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelFileUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFileOpen))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        buttonEditMode.setText(" Edit  ");
        buttonEditMode.setToolTipText("Go to Edit Mode");
        buttonEditMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditModeActionPerformed(evt);
            }
        });

        buttonPreviewMode.setText("Preview");
        buttonPreviewMode.setToolTipText("Go to Preview Mode");
        buttonPreviewMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreviewModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(buttonEditMode, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonPreviewMode, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEditMode)
                    .addComponent(buttonPreviewMode))
                .addContainerGap(337, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditModeActionPerformed
        // Handling Edit Mode
        jPanel1.setVisible(true);
        labelPreview.setVisible(false);
        
        buttonPreviewMode.setEnabled(true);
        buttonEditMode.setEnabled(false);
    }//GEN-LAST:event_buttonEditModeActionPerformed

    private void buttonPreviewModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreviewModeActionPerformed
      // Validating Input Text box
    if (jTextArea1.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this,"Please Enter the Problem Description.","LAITS Error...",JOptionPane.ERROR_MESSAGE);    
      return;
    }
    if (labelFileUrl.getText().compareTo("No File Selected.")==0) {
      JOptionPane.showMessageDialog(this,"Please select the Problem Image. Default Image will be used if no image is selected.","LAITS Warning...",JOptionPane.WARNING_MESSAGE);      
    }
      
      // Handling Preview Mode
        jPanel1.setVisible(false);                
        
        labelPreview.setVisible(true);
       
        String problemDetails = constructPreviewText(jTextArea1.getText());
        System.out.println(problemDetails);
        labelPreview.setText(problemDetails);                
        buttonPreviewMode.setEnabled(false);
        buttonEditMode.setEnabled(true);
        
    }//GEN-LAST:event_buttonPreviewModeActionPerformed

    // Helper Methods 
    private String constructPreviewText(String rawText){
        File file = new File("src/amt/images/asu.jpg");               
        String imageUrl = "file:"+File.separator+File.separator+file.getAbsolutePath();
        
        if(rawText==null || rawText.isEmpty()){
            rawText = "No problem description provided";
        }
        
        if (labelFileUrl.getText().compareTo("No File Selected.")!=0) {
          // Set default URL to ASU Image URL
          imageUrl = "file:"+File.separator+File.separator+labelFileUrl.getText();
        }
        
        // Replacing '\n' with <br/>
        rawText = rawText.replace("\n", "<br/>");
        
        String htmlText="<html>"+
                                "<table width='800'><tr><td width=25%>"+"<img src='"+imageUrl+"' height='240' width='240' alt='Problem Image Not Selected.'/>"+"</td>"
                                +"<td style='margin-left:30px;' valign='top' width='75%'>"+rawText+"</td>"
                                +"</tr></table>";;
        return htmlText;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditMode;
    private javax.swing.JButton buttonFileOpen;
    private javax.swing.JButton buttonPreviewMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelFileUrl;
    private javax.swing.JLabel labelPreview;
    // End of variables declaration//GEN-END:variables
}
